name: dbt Production Run on Push to Master

on:
  push:
    branches:
      - 'main'

jobs:
  run_dbt_on_merge_to_master:
    name: dbt Production Run on Push to Main
    runs-on: ubuntu-latest

    env:
      DBT_API_KEY:             ${{ secrets.DBT_API_TOKEN }}
      DBT_URL:                 https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
      DBT_JOB_CAUSE:           'Github Actions - Push to Main' # provide a descriptive job cause here for easy debugging down the road
      DBT_ACCOUNT_ID:          ${{ secrets.DBT_ACCOUNT_ID }}
      DBT_PROJECT_ID:          ${{ secrets.DBT_PROJECT_ID }}
      DBT_PR_JOB_ID:           ${{ secrets.DBT_JOB_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      run: |
        python -u ./python/run_and_monitor_dbt_cloud_job.py
